x-logging: &default-logging
  driver: "json-file"
  options:
    max-file: "5"
    max-size: "10m"


services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 6070:6070
    logging: *default-logging
