import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ContextLayout from "@/actions/UserContext/UserProvider";
import { UserProvider } from "@/actions/UserContext/UserContext";
import Header from "@/components/core/Header/Header";
import Footer from "@/components/core/Footer/Footer";
import MobileSidebar from "@/components/core/Header/MobileSidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <div className="hidden lg:block">
            <Header />
          </div>
          <div className="lg:hidden">
            <MobileSidebar />
          </div>
          {children}
          <div>
            <Footer />
          </div>
        </UserProvider>
      </body>
    </html>
  );
}
